{% set version = "1.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-snotelr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/snotelr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/snotelr/snotelr_{{ version }}.tar.gz
  sha256: f7f720ee9067474ddc72e24a2ff34b0ce284479e8fa10e23a340698c328c25eb

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-httr
    - r-memoise
    - r-rvest
    - r-shiny
  run:
    - r-base
    - r-dplyr
    - r-httr
    - r-memoise
    - r-rvest
    - r-shiny

test:
  commands:
    - $R -e "library('snotelr')"           # [not win]
    - "\"%R%\" -e \"library('snotelr')\""  # [win]

about:
  home: https://github.com/bluegreen-labs/snotelr
  license: AGPL-3.0-only
  summary: Programmatic interface to the 'SNOTEL' snow data (<https://www.nrcs.usda.gov/wps/portal/wcc/home>). Provides easy downloads of snow data into your R work space or a local directory. Additional post-processing routines to extract snow season indexes are provided.
  license_family: AGPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# The original CRAN metadata for this package was:
# Package: snotelr
# Title: Calculate and Visualize 'SNOTEL' Snow Data and Seasonality
# Version: 1.1
# Authors@R: c(person( family = "Hufkens", given = "Koen", email = "koen.hufkens@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-5070-8109")), person(given = "BlueGreen Labs", role = c("cph", "fnd")))
# Description: Programmatic interface to the 'SNOTEL' snow data (<https://www.nrcs.usda.gov/wps/portal/wcc/home>). Provides easy downloads of snow data into your R work space or a local directory. Additional post-processing routines to extract snow season indexes are provided.
# URL: https://github.com/bluegreen-labs/snotelr
# BugReports: https://github.com/bluegreen-labs/snotelr/issues
# Depends: R (>= 3.6)
# Imports: shiny, httr, utils, stats, rvest, magrittr, memoise
# Suggests: knitr, rmarkdown, covr, testthat, shinydashboard, leaflet, plotly, DT
# VignetteBuilder: knitr
# License: AGPL-3
# ByteCompile: true
# RoxygenNote: 7.2.1
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2022-08-20 13:34:04 UTC; khufkens
# Author: Koen Hufkens [aut, cre] (<https://orcid.org/0000-0002-5070-8109>), BlueGreen Labs [cph, fnd]
# Maintainer: Koen Hufkens <koen.hufkens@gmail.com>
# Repository: CRAN
# Date/Publication: 2022-08-20 21:50:02 UTC
# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
